### ISSUE TITLE
Mention that svg-lib is required. paw-pbm-enable should probably be set to nil

### ISSUE THREAD

**Issue by johanwiden** [chenyanming/paw#4]
The README should mention that svg-lib is required.
Currently paw-svg.el does not call svg-lib, because paw-svg-enable is nil, but there are still references in the code to svg-lib functions. (I tried setting paw-svg-enable to t, but that did not change the output of paw-note.el)

Currently paw-pbm-enable is set to t. But paw then refers to files that have to be installed in a subdirectory of "doom-private-dir", so it is probably best if the public version of paw has paw-pbm-enable set to nil.

I put the following in my Doom Emacs config:
  (after! paw
    (setq paw-pbm-enable nil))

**Comment by chenyanming** [comment]
Problem fixed.

**Comment by johanwiden** [comment]
Yes, I can now use svg-lib!
I had no luck with setting paw-pbm-enable to t: I still get empty square buttons, even though the path to the image directory is as expected.

**Comment by chenyanming** [comment]
Did you download the images? `(package! paw :recipe (:host github :repo "chenyanming/paw" :files ("*")))`

**Comment by johanwiden** [comment]
Yes, the images are downloaded. And if I browse the image directory in dired, I can view the images.

**Comment by johanwiden** [comment]
Now paw-pbm-enable works for me! I do not know why it did not before. But in between I updated the package recipe to include :files ("*"), and synced doom emacs again.
I also get a highlighted button when I click on the button. The svg images are highlighted as soon as I hover over them.

**Comment by johanwiden** [comment]
No longer a problem.
