### ISSUE TITLE
About the desktop environment of developer

### ISSUE THREAD

**Issue by dekoponTree** [chenyanming/paw#5]
Thanks for your contribution and such an awesome work.

May I ask what's the development environment of yours, i.e., the OS, etc.

I use macOS, and notice that EAF appears frequently, which is notoriously not friendly for macOS users.

For better experience, maybe it's good to align with your system environment.

I will be appreciated if you could share your own system environment. Thanks.

**Comment by chenyanming** [comment]
I am using ubuntu 22.04, and Android 14.

I am curious of 'EAF appears frequently'. Was it an issue of paw?

**Comment by dekoponTree** [comment]
Thanks for your timely response.

As per your question, exactly not. Just because I saw your Emacs has integrated with browser seamlessly, which might be attributed to eaf-browser.

While eaf-browser doesn't support macOS well, so I wanna make it clear that what os you are using, with the purpose of alignment between my DE and yours.
